apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./apps
    repoURL: https://gitlab.sikalabs.com/ondrejsika-random/2024-09-18_argocd-apps-test-values-in-files.git
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Secret
metadata:
  name: repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default
  type: git
  url: https://gitlab.sikalabs.com/ondrejsika-random/2024-09-18_argocd-apps-test-values-in-files.git
  username: token
  password: glpat-xeU_ksCKbeXSSzzsz6Ny
